# Tensors
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)


Each tensor has a data type and a shape.

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.



### Creating tensor

In [1]:
#importing library
import tensorflow as tf

C:\Users\mdram\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
string=tf.Variable('this is a string', tf.string)   #datatype, shape,rank
number=tf.Variable(23, tf.int32)
floating=tf.Variable(2.3, tf.float64)

In [16]:
s =tf.Variable(st)
tf.rank(s)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [3]:
tf.shape([2,3,4]), tf.shape('STRING')   #'SHAPE'

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>,
 <tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>)

In [4]:
tf.size(64)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
num=23
num.bit_length()

5

### Rank/Degree
Number of dimension linked with the tensor?

In [6]:
rank1t=tf.Variable(['some value'], tf.string)  # 1D
rank2t=tf.Variable([["customer", "location"],['jal',"berlin"]], tf.string) # 2D
rank1t

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'some value'], dtype=object)>

In [18]:
tf.rank(rank2t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [23]:
tf.rank(rank2t), tf.rank(rank1t)  # Checking the relavant rank/dimension

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [25]:
rank1t.shape, rank2t.shape    # Checking shape:The amount of elements exist in each dimension

(TensorShape([1]), TensorShape([2, 2]))

expl: 2 list, 2 elements each

### Changing shape

In [20]:
ten1=tf.ones([1,2,3]) #one interior list, which contain 2_list and each list contain 3 elements
ten1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [22]:
ten2=tf.reshape(ten1, [3,2,1])
ten3=tf.reshape(ten2, [3, -1])
ten2, ten3

(<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
 array([[[1.],
         [1.]],
 
        [[1.],
         [1.]],
 
        [[1.],
         [1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [29]:
t= tf.ones([2,4,9])
t

<tf.Tensor: shape=(2, 4, 9), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32)>

In [37]:
t1=tf.reshape(t, [3,8,3])
t1

<tf.Tensor: shape=(3, 8, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [30]:
t= tf.zeros([2,4,9])
t

<tf.Tensor: shape=(2, 4, 9), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

### Types of Tensors
- Variable
- Constant
- Placeholder
- SparseTensor.
- other..

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.